name: Auto Sync


on:
  schedule:
  - cron:  "20 * * * *"

  workflow_dispatch:


jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: ls
      run: ls -la

    
    - name: repo-sync
      id: sync
      uses: lemonadestar-lordsea/github-sync@dev
      with:
        source_repo: "https://dev.sp-tarkov.com/SPT-AKI/Modules.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.PAT }}
        sync_tags: "true"    
    
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3.11
    
    - name: print results
      run: echo "{${{ steps.sync.outputs.result_push }}}"
